### ISSUE TITLE
Password could not be checked: TypeError: Cannot read property 'error' of undefined

### ISSUE THREAD

**Issue by Man-in-Black** [ochorocho/syspass-addon#13]
I managed to install syspass manually in Google Chrome.
But now when I try to establish a connection, I get the following error: Password could not be checked: TypeError: Cannot read property 'error' of undefined
I created an API token and entered it.
How can it fail?
Additional info: The syspass can only be reached internally or via VPN, but access is secured by SSL with a wildcard certificate.

Thank you for your help.

Best wishes
Sascha

**Comment by ochorocho** [comment]
Just tested version 1.6.3 with chrome  80.0.3987.149. I do not get any errors. 

On which page do you get this error?
What version of chrome are you using?
Did you set both API Permissions (Search for accounts/View Password) with the same password?

The domain you setup has to be available through VPN.

**Comment by ochorocho** [comment]
Did not get any response. Feel free to re-open this issue if this occurs again.
