### ISSUE TITLE
Chrome extension: Canot decode "icon-dark.svg"

### ISSUE THREAD

**Issue by ucola** [ochorocho/syspass-addon#14]
hi all

with the latest chrome browser, I cannot install the syspass addon on https://chrome.google.com/webstore/detail/syspass/iekmmiiflmajnlogcmljnpeinnkicdhg

I became an error:  Canot decode "icon-dark.svg"

**Comment by ochorocho** [comment]
Hey, currently Chrome webstore refuses to add the addon.
But you can drag&drop the plugin to chromes addon page to install it.
Just download the zip file from https://github.com/ochorocho/syspass-addon/releases/tag/1.6.3

**Comment by slimco** [comment]
I have same problem, now in market chrome is version 1.6.4.

**Comment by ochorocho** [comment]
This seems like the main issue. Chrome not supporting SVG icons.
https://bugs.chromium.org/p/chromium/issues/detail?id=29683

Replaced the SVG icons with PNG.

Version 1.6.5 should fix the problem

https://github.com/ochorocho/syspass-addon/releases/tag/1.6.5

**Comment by ochorocho** [comment]
Works now on Chrome and Edge
