### ISSUE TITLE
<input type="text"> assumption

### ISSUE THREAD

**Issue by andr1908m** [ochorocho/syspass-addon#15]
Hi

I found in line 79:

`
usernameField = (typeof (passwordField) !== 'undefined' && passwordField !== null) ? passwordField.closest('form').querySelectorAll(  'input[type="text"]'  )[0] : null
`

The code assumes that the nearest input[type="text"] will be ok, but i think it should also use the email as a backup. I think this would be a potential fix.

`
usernameField = (typeof (passwordField) !== 'undefined' && passwordField !== null) ? passwordField.closest('form').querySelectorAll(  'input[type="text"], input[type="email"]'  )[0] : null
`

**Comment by ochorocho** [comment]
@andr1908m thanks for your report.

Seems like a good idea to have email als fallback. 👍

**Comment by ochorocho** [comment]
Change code according to your suggestion and released version 1.6.4

Feel free to re-open this issue if the problem still exists.
