### ISSUE TITLE
General question about security

### ISSUE THREAD

**Issue by vmario89** [ochorocho/syspass-addon#2]
Hi,
just one question which came to my mind. I am not a (web) developer. How are token and password from this extension secured/stored in Firefox? Firefox itself using Lockwise (https://blog.mozilla.org/firefox/de/firefox-sorgt-mit-lockwise-fuer-noch-mehr-sicherheit-fuer-deine-passwoerter/). 

regards, Mario :-)

**Comment by ochorocho** [comment]
Well, i'm using the browsers api:
https://github.com/ochorocho/syspass-firefox/blob/master/addon/options/options.js#L91

Not sure if its the best method.
