### ISSUE TITLE
Problem is opening new tab "about: blank"

### ISSUE THREAD

**Issue by slakhneko** [ochorocho/syspass-addon#20]
Hi.
There is a problem.
After installing the extension when opening on "Open SysPass" a new tab "about: blank" opens and nothing happens.
Similar observations in Firefox and Google Chrome

**Comment by ochorocho** [comment]
Did you configure the Plugin on the addons page and entered a valid URL?

**Comment by slakhneko** [comment]
Everything worked out! Thank you
