### ISSUE TITLE
Could not connect to sysPass, check your API key

### ISSUE THREAD

**Issue by Smax2k** [ochorocho/syspass-addon#29]
Hello,

SysPass is installed on a shared hosting with a valid https (PHP 7.2).

I created an API authorization with a password and I have the token (in Action i have set Password view).

But the addon throws an error: unable to connect to sysPass, check your API key.

I don't understand what i was missing.

Thank you

**Comment by Smax2k** [comment]
And in Action i have set Password view.

**Comment by ochorocho** [comment]
See the video if you have setup the API keys correctly https://cloud.knallimall.org/s/6ZpacXCeEMWpBEN
If so, it would be great to know which browser you are using and if you get any errors in the plugin.

For Debugging go to url `about:debugging#/runtime/this-firefox` in firefox.

**Comment by dplmr** [comment]
I experienced this issue on Chrome on a fresh sysPass installation. Despite the "check your API key" error, I saw a successful authorization in the Event Log. By trial and error, I found the fix was to have at least 1 account returned by sysPass.

**Comment by poolneo** [comment]
Hello,
I have the same problem. Debian 10, Apache2, sysPass 3.1.2, sysPass plugin 1.6.7 from firefox, Firefox 81.0.2.
Use local IP and self signed certificate.

Event log from firefox:
![obraz](https://user-images.githubusercontent.com/73332625/96971445-63ee7300-1515-11eb-8e0c-ef6ae5f50258.png)

Can you help me? Thank you

**Comment by ochorocho** [comment]
@poolneo do you have at least one account which is supposed to show up? ...

**Comment by poolneo** [comment]
Yes, i have two account. First time I try connect to admin, second time i create new user but still not work

![obraz](https://user-images.githubusercontent.com/73332625/97003382-a5921480-153b-11eb-8ae0-a30764f789e0.png)

**Comment by ochorocho** [comment]
By Account i ment something like this:

<img width="1348" alt="grafik" src="https://user-images.githubusercontent.com/4623070/97005214-6f09c900-153e-11eb-890a-effcd6bec6aa.png">

Not the user accounts. IIRC, i check if there is any results in a search. Maybe it makes sense just to check the status code.

**Comment by ochorocho** [comment]
For testing you can try to use http://demo.syspass.org/ ... this should work.

**Comment by poolneo** [comment]
Yep, now it's work 👍 
Thank you, where i can do donate you?

**Comment by ochorocho** [comment]
👍 Great to hear its working :-)

Use the Github sponsor button: https://github.com/sponsors/ochorocho Not sure if it is possible to do a single Donation

**Comment by invisibletint** [comment]
Hi,
I have got the same issue as above...
URL, API Token, API Password are all filled in and filled in right but I keep getting "Could not connect to sysPass, check your API key".
First I haven't even found API Token, now I have got it but can't enable Firefox Addon with it...
What is API Key? Token or Password?

Great work though, it is looking great, I really appreciate it.

**Comment by ochorocho** [comment]
@invisibletint the user needs to have access to at least one account. This way i determine if the connections was successful.
