### ISSUE TITLE
Parsing of domains and subdomains

### ISSUE THREAD

**Issue by vmario89** [ochorocho/syspass-addon#3]
Hi, for some pages i recognized that it shows a lot of accounts from sub domains. Tihs will mess up my login dropdown. For our wordpress page i got about 60 accounts shown. Thats clearly too much :-D

imagine you run an organization and host sub1.domain.tld sub2.domain.tld etc. and you go on the main homepage domain.tld to perform a login. you will get all logins auf subdomain services. 

regards, Mario

**Comment by ochorocho** [comment]
Hey, the thing is the API search does work if the entire url including protocol is not working.
As a alternative i was thinking of using this package https://www.npmjs.com/package/leven to work around this issue.

The result would be still a long list, but the best matches would appear on the very top.
What do you think? :-)

**Comment by ochorocho** [comment]
And of course its possible to limit the results.

**Comment by ochorocho** [comment]
v.1.5.1 adds support for dropdown filter. So when you type the dropdown gets filtered.
On top of that there is now a setting to disable the dropdown.
There is now a toolbaricon which you can use to fill out the form with credentials
