### ISSUE TITLE
Android compability

### ISSUE THREAD

**Issue by vmario89** [ochorocho/syspass-addon#4]
Hi,
i can confirm that it works really good in android too even it is not supported yet officially.

so far i just have a small visual thing:
![grafik](https://user-images.githubusercontent.com/5631071/73612777-fac57900-45ee-11ea-9bdd-989fd181cbfe.png)

that checkbox is nearly invisible on mobile view

**Comment by vmario89** [comment]
![grafik](https://user-images.githubusercontent.com/5631071/73612786-247ea000-45ef-11ea-84f1-e601c08921dd.png)

**Comment by ochorocho** [comment]
Styled checkbox and enabled support for firefox android
