### ISSUE TITLE
Some smart button to route to syspass homepage

### ISSUE THREAD

**Issue by vmario89** [ochorocho/syspass-addon#5]
hi,
as you implemented that cool small button at the corner at the top right corner: it would be cool if there would be some button to go directly to syspass instance by button (like a bookmark)
![grafik](https://user-images.githubusercontent.com/5631071/73612804-5859c580-45ef-11ea-9faa-97647d880a21.png)
![grafik](https://user-images.githubusercontent.com/5631071/73612806-5ee83d00-45ef-11ea-8da1-aa3e5292a3c1.png)

**Comment by ochorocho** [comment]
Added a button to directly jump to sysPass installation in Version 1.6

<img width="281" alt="Bildschirmfoto 2020-02-10 um 00 56 01" src="https://user-images.githubusercontent.com/4623070/74112841-2a045900-4ba0-11ea-84b5-fdbdf6d6efde.png">
