### ISSUE TITLE
Enhancement

### ISSUE THREAD

**Issue by vmario89** [ochorocho/syspass-addon#6]
Hi,
i think for general enhancement it will be easier for "normal" users if the backend mask just would directly validate api token and passwort by validating the json API result (when saving the preferences). if it fails it should pop up some hint like "ask your admin to configure properly" bla bla :)

![grafik](https://user-images.githubusercontent.com/5631071/73613172-5b56b500-45f3-11ea-9021-3f2325840c46.png)

cheers, Mario

**Comment by ochorocho** [comment]
Now running test for both, search and password api request and returns appropriate messages.
