### ISSUE TITLE
Nextcloud Login problem

### ISSUE THREAD

**Issue by Nie-Oh** [ochorocho/syspass-addon#7]
Hello,

i want to login to my nextcloud instance. The login is filled, but wen i click the singin button i got wrong password.
but it is the right login data. i save this login in firefox, then it works fine.

**Comment by ochorocho** [comment]
Hey, thanks for your report.

For some reason Nexcloud username will be emptied by some javascript in Nextcloud.
When you type only one letter, delete it and you hit the login button i'll will work.

Could not find a solution to this so far.

**Comment by Nie-Oh** [comment]
Hallo Ochorocho,

Englisch ist nicht so mein Ding. Deshalb schreibe ich mal auf Deutsch.
Ist es möglich die die Vorschläge wieter einzugrenzen. wir arbeiten viel mit Unterverzeichnissen.

http://test.de/test1
http://test.de/test2
...

Jetzt bekommen wir dadurch eine Ellenlange liste. Da ja nur nach der URL sortiert wird. Kann man nicht noch ein Unterverzeichnis mit einbeziehen?

**Comment by ochorocho** [comment]
@Nie-Oh verion 1.6.1 sucht jetzt mit Unterverzeichnis nicht nur hostname.
